### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by lucasrg** [lucasrg/verse-boot#1]
- [x] Internal error page (500)
- [x] Redirection (301, 302, 303, 307)
- [x] Scroll position on navigation
- [x] API calls
- [x] Auth
- [x] Styling
- [x] Server side API + MongoDB support
- [ ] Responsiveness
- [ ] Readme / Getting start doc
